# Generated by Django 4.2.23 on 2025-09-01 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_eliminacionempresa'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={},
        ),
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='orden',
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
