# Generated by Django 4.2.23 on 2025-09-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_usuario_cliente_usuario_id'),
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='observaciones',
            new_name='observacion',
        ),
        migrations.RenameField(
            model_name='lectura',
            old_name='consumo',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='lectura',
            name='empresa_slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
