# Generated by Django 4.2.23 on 2025-09-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_eliminacionempresa'),
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='sector',
        ),
        migrations.AddField(
            model_name='aviso',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(default='Aviso sin título', max_length=100),
        ),
    ]
