# Generated by Django 4.2.23 on 2025-09-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_remove_aviso_cliente_remove_aviso_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
