# Generated by Django 4.2.23 on 2025-09-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0007_trabajador'),
        ('empresas', '0003_eliminacionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compras', 'Compras'), ('ventas', 'Ventas'), ('retenciones', 'Retenciones')], max_length=20)),
                ('periodo', models.CharField(max_length=7)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('validado', 'Validado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Libro Contable',
                'verbose_name_plural': 'Libros Contables',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado')], default='vigente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Contrato Laboral',
                'verbose_name_plural': 'Contratos Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
