# Generated by Django 4.2.23 on 2025-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('rut_emisor', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('33', 'Factura'), ('34', 'Factura Exenta'), ('46', 'Boleta'), ('56', 'Nota Débito'), ('61', 'Nota Crédito')], max_length=10)),
                ('folio', models.IntegerField()),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('rut_receptor', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('33', 'Factura'), ('34', 'Factura Exenta'), ('39', 'Boleta'), ('56', 'Nota Débito'), ('61', 'Nota Crédito')], max_length=10)),
                ('folio', models.IntegerField()),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientocontable',
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='CuentaContable',
        ),
        migrations.DeleteModel(
            name='MovimientoContable',
        ),
    ]
