# Generated by Django 4.2.23 on 2025-09-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_documentocompra_documentoventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('validado', 'Validado'), ('error', 'Con error')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
