# Generated by Django 4.2.23 on 2025-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_librosii'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompra',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librosii',
            name='cuenta_afecta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librosii',
            name='cuenta_egreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librosii',
            name='cuenta_exenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librosii',
            name='cuenta_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librosii',
            name='desde_comprobante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librosii',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('retenciones', 'Retenciones'), ('ingreso_retenciones', 'Ingreso de retenciones')], max_length=25),
        ),
    ]
