# Generated by Django 4.2.23 on 2025-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_documentocompra_cuenta_contable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosii',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros_sii/'),
        ),
    ]
