# Generated by Django 4.2.23 on 2025-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('rut_trabajador', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('jornada', models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial'), ('turnos', 'Por turnos')], max_length=50)),
                ('sueldo_base', models.PositiveIntegerField()),
                ('gratificacion', models.PositiveIntegerField(default=0)),
                ('bonos', models.PositiveIntegerField(default=0)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('faena', 'Por Faena')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
