# Generated by Django 4.2.23 on 2025-09-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiniquitoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('fecha_finiquito', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('indemnizacion', models.PositiveIntegerField(default=0)),
                ('vacaciones_pendientes', models.PositiveIntegerField(default=0)),
                ('otros', models.PositiveIntegerField(default=0)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='finiquitos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.contratolaboral')),
            ],
        ),
    ]
