# Generated by Django 4.2.23 on 2025-09-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_finiquitolaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=7)),
                ('sueldo_base', models.PositiveIntegerField()),
                ('gratificacion', models.PositiveIntegerField(default=0)),
                ('bonos', models.PositiveIntegerField(default=0)),
                ('descuentos', models.PositiveIntegerField(default=0)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='liquidaciones/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.contratolaboral')),
            ],
        ),
    ]
