# Generated by Django 4.2.23 on 2025-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_liquidacionlaboral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidacionlaboral',
            old_name='descuentos',
            new_name='afp',
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='dias_ausente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='dias_licencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='dias_vacaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='otros_descuentos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='salud',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='seguro_cesantia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
