# Generated by Django 4.2.23 on 2025-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_rename_descuentos_liquidacionlaboral_afp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='afp',
            field=models.CharField(choices=[('modelo', 'AFP Modelo'), ('provida', 'AFP Provida'), ('cuprum', 'AFP Cuprum'), ('habitat', 'AFP Habitat'), ('planvital', 'AFP PlanVital')], default='modelo', max_length=50),
        ),
        migrations.AddField(
            model_name='contratolaboral',
            name='salud',
            field=models.CharField(choices=[('fonasa', 'Fonasa'), ('colmena', 'Colmena'), ('banmedica', 'Banmédica'), ('cruz_blanca', 'Cruz Blanca'), ('vida_tres', 'Vida Tres')], default='fonasa', max_length=50),
        ),
    ]
