# Generated by Django 4.2.23 on 2025-09-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_contratolaboral_afp_contratolaboral_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='sistema_gratificacion',
            field=models.CharField(choices=[('art_47', 'Proporcional a utilidades (Art. 47)'), ('art_50', '25% del sueldo base (Art. 50)'), ('sin_gratificacion', 'No aplica')], default='art_50', max_length=20),
        ),
    ]
