# Generated by Django 4.2.23 on 2025-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0007_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='liquido_calculado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
