# Generated by Django 4.2.23 on 2025-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0008_liquidacionlaboral_liquido_calculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionlaboral',
            name='liquido_calculado',
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='horas_extra_100',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='horas_extra_50',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
