# Generated by Django 4.2.23 on 2025-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0009_remove_liquidacionlaboral_liquido_calculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolaboral',
            name='tipo_gratificacion',
            field=models.CharField(choices=[('fija', 'Fija mensual (25%)'), ('proporcional', 'Proporcional a utilidades')], default='fija', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratolaboral',
            name='salud',
            field=models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre'), ('fuerzas armadas', 'Fuerzas Armadas')], default='fonasa', max_length=50),
        ),
    ]
