# Generated by Django 4.2.23 on 2025-08-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_email_cliente_latitude_cliente_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
