# Generated by Django 4.2.23 on 2025-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_empresa_cliente_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
