# Generated by Django 4.2.23 on 2025-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_usuario_id_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
