# Generated by Django 4.2.23 on 2025-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('color_dashboard', models.CharField(default='#008000', max_length=20)),
            ],
        ),
    ]
