# Generated by Django 4.2.23 on 2025-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sectores_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
